import { Inter, Noto_Sans } from "next/font/google";
import "./globals.css";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] });
const notoSans = Noto_Sans({ subsets: ['cyrillic'], weight: ['300', '400', '500', '600', '700', '800'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} container mx-auto px-4 antialiased bg-body_bg text-night_green`}>
        <TheHeader />
        <main className="">
          {children}
        </main>
        <TheFooter />
      </body>
    </html>
  );
}
